version: '3'
services:
  pgadmin-ppdd:
    image: dpage/pgadmin4:4.16
    volumes:
      - pgadmin_volume:/root/.pgadmin
    ports:
      - 8101:80
    restart: unless-stopped
    depends_on:
      - postgres-ppdd
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
  postgres-ppdd:
    image: postgres:11.8
    restart: always
    ports:
      - 8102:5432
    environment:
      POSTGRES_DB: cwa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  edus:
    build:
      context: ./
      dockerfile: ./services/edus/Dockerfile
  ppac:
    build:
      context: ./
      dockerfile: ./services/ppac/Dockerfile
volumes:
  pgadmin_volume:
